# Site
name: 'WizeVest'
description: 'WizeVest | Investing and Business made simple.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
# disqus: 'demowebsite'
# email: 'wowthemesnet@gmail.com' # used in formspree.io call on contact us page
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    jeff:
      name:           Jeff G. | MBA
      key:           jeff
      # site:           https://www.wowthemes.net
      avatar:         assets/images/author-jeff.png
      bio:            "My name is Jeff, I enjoy gaining understanding about business and investing, especially from a financial perspective. I hope the knowledge I convey through my articles helps you along your business and investing journey!"
      # twitter:        https://twitter.com/wowthemesnet

 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: jeff
      avatar: /assets/images/author-jeff.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]